---
title:  "Pilot A Analysis"
author: "Vivian Xiao"
date: "February 26, 2017"
output: 
  html_document:
    highlight: pygments
    theme: flatly
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages}
#load packages needed for this assignment
library(tidyverse)
library(psych)
```


#Data cleaning
```{r clean data}
d = read.csv("~/Desktop/PSYC254/livingston2012/Pilot_A.csv")


d.tidy = d %>%
  filter(manipcheck == 0) %>%
  select(T_race, T_gender, T_behavior, Q11_1:Q11_4, Q13_1, Q14_1, Q17,Q19,Q21,Q23,Q25, Q27,Q29) %>%
  rename(lead_well=Q11_1) %>%
  rename(lead_max=Q11_2) %>%
  rename(lead_admire=Q11_3) %>%
  rename(lead_respect=Q11_4) %>%
  rename(lead_salary = Q13_1) %>%
  rename(PvsS = Q14_1) %>%
  rename(race = Q17) %>%
  rename(age = Q19) %>%
  rename(gender = Q21) %>%
  rename(educ = Q23) %>%
  rename(workexp = Q25) %>%
  rename(pol_s = Q27) %>%
  rename(pol_e = Q29)

d.tidy$T_race = as.factor(d.tidy$T_race)
levels(d.tidy$T_race)[1] = "white"
levels(d.tidy$T_race)[2] = "black"
d.tidy$T_gender = as.factor(d.tidy$T_gender)
levels(d.tidy$T_gender)[1] = "male"
levels(d.tidy$T_gender)[2] = "female"
d.tidy$T_behavior = as.factor(d.tidy$T_behavior)
levels(d.tidy$T_behavior)[1] = "agentic"
levels(d.tidy$T_behavior)[2] = "communal"


d.tidy$lead_well = as.numeric(d.tidy$lead_well) 
d.tidy$lead_max = as.numeric(d.tidy$lead_max)
d.tidy$lead_admire = as.numeric(d.tidy$lead_admire)
d.tidy$lead_respect = as.numeric(d.tidy$lead_respect)
d.tidy$lead_salary = as.numeric(d.tidy$lead_salary)

d.tidy$leadev = rowMeans(d.tidy[,4:8]) #make composite 
lead = matrix(c(d.tidy$lead_well, d.tidy$lead_max, d.tidy$lead_admire, d.tidy$lead_respect,d.tidy$lead_salary), ncol=5)
alpha(lead) #reliability check
```


#Analysis
```{r analysis}
#main analyses from livingston et al
summary(lm(leadev ~ T_race*T_gender*T_behavior, d.tidy)) #main 3 way interaction (leader evaluations)

d.women = d.tidy %>%
  filter(T_gender == "female")

summary(lm(leadev ~ T_race*T_behavior, d.women)) #2 way for women (leader evaluations)

d.men = d.tidy %>%
  filter(T_gender == "male")

summary(lm(leadev ~ T_race*T_behavior, d.men)) #2 way for men (leader evaluations)


summary(lm(PvsS ~ T_race*T_gender*T_behavior,d.tidy)) #3 way interaction (attribution of behavior)
summary(lm(PvsS ~ T_race*T_behavior,d.women)) #2 way for women (attribution of behavior)
summary(lm(PvsS ~ T_race*T_behavior,d.men)) #2 way for men (attribution of behavior)
summary(lm(PvsS ~ T_race,d.tidy)) #main effect of race
```

